package crmapplicationdesktop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Utilities.DateCleanser;
import crmapplicationdesktop.entity.*;
import javax.persistence.*;
import java.util.*;
/**
 *
 * @author user
 */
public class AddCampaign extends javax.swing.JFrame {

    /**
     * Creates new form AddCampaign
     */
    public AddCampaign() {
        initComponents();
        populateManagers();
        populateCampaignTypes();
        populateProducts();
    }
    
    
    
    private static final String[] CAMPAIGN_TYPES = {"Weekly", "Monthly", "Quarterly", "Holiday"};
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("CRMApplicationDesktopPU");
        EntityManager em = emf.createEntityManager();
        
        //create a query to retrieve all account managers
        TypedQuery<Accountmanagers> query = em.createQuery("SELECT c FROM Accountmanagers c", Accountmanagers.class);
        List<Accountmanagers> MANAGERS = query.getResultList();
        
        //create query to retrieve product information
        TypedQuery<Products> productQuery = em.createQuery("SELECT p FROM Products p", Products.class);
        List<Products> PRODUCTS = productQuery.getResultList();
        
        
        private void populateCampaignTypes(){
            for(String types: CAMPAIGN_TYPES){
                campaignType.addItem(types);
            }
            campaignType.setEditable(true);
        }
        
         private void populateManagers(){
         for(Accountmanagers person: MANAGERS){
             String fullName = person.getFirstName() + " " + person.getLastName();
             campaignManager.addItem(fullName);
             campaignManagerID.addItem(person.getAccountManagerId().toString());
         }
         
     }
         
         private void populateProducts(){
             for(Products prod: PRODUCTS){
                 campaignProduct.addItem(prod.getProductName());
                 campaignProductID.addItem(prod.getProductId().toString());
             }
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campaignNameLabel = new javax.swing.JLabel();
        campaignTypeLabel = new javax.swing.JLabel();
        campManagerLabel = new javax.swing.JLabel();
        campaignManagerIDLabel = new javax.swing.JLabel();
        campaignStartLabel = new javax.swing.JLabel();
        campaignEndLabel = new javax.swing.JLabel();
        campaignProductIDLabel = new javax.swing.JLabel();
        campaignProductLabel = new javax.swing.JLabel();
        salesValueLabel = new javax.swing.JLabel();
        salesVolumeLabel = new javax.swing.JLabel();
        campaignName = new javax.swing.JTextField();
        campaignStart = new javax.swing.JTextField();
        campaignEnd = new javax.swing.JTextField();
        salesValue = new javax.swing.JTextField();
        salesVolume = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        campaignType = new javax.swing.JComboBox<>();
        campaignManager = new javax.swing.JComboBox<>();
        campaignManagerID = new javax.swing.JComboBox<>();
        campaignProduct = new javax.swing.JComboBox<>();
        campaignProductID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Add Campaign");

        campaignNameLabel.setText("Campaign Name");

        campaignTypeLabel.setText("Campaign Type");

        campManagerLabel.setText("Campaign Manager");

        campaignManagerIDLabel.setText("Campaign Manager ID");

        campaignStartLabel.setText("Campaign Start");

        campaignEndLabel.setText("Campaign End");

        campaignProductIDLabel.setText("Campaign Product ID");

        campaignProductLabel.setText("Campaign Product");

        salesValueLabel.setText("Campaign Sales Value Target");

        salesVolumeLabel.setText("Campaign Sales VolumeTarget");

        campaignName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campaignNameActionPerformed(evt);
            }
        });

        campaignStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campaignStartActionPerformed(evt);
            }
        });

        campaignEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campaignEndActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
                HandleResetform(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HandleSubmit(evt);
            }
        });

        campaignType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        campaignManager.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        campaignManagerID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        campaignProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        campaignProductID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campaignNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campaignTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(salesVolumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campManagerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campaignManagerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campaignStartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campaignEndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campaignProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campaignProductIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campaignName)
                    .addComponent(campaignType, 0, 510, Short.MAX_VALUE)
                    .addComponent(campaignManager, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campaignManagerID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campaignStart)
                    .addComponent(campaignEnd)
                    .addComponent(campaignProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campaignProductID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesValue)
                    .addComponent(salesVolume))
                .addContainerGap(925, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campaignNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campaignName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campaignTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campaignType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campManagerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(campaignManager, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campaignManagerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campaignManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campaignStartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campaignStart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campaignEndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campaignEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campaignProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(campaignProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campaignProductIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campaignProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salesValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(salesValue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salesVolumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salesVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(submitBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetBtnActionPerformed

    private void campaignStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campaignStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campaignStartActionPerformed

    private void campaignEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campaignEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campaignEndActionPerformed

    private void campaignNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campaignNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campaignNameActionPerformed

    private void HandleSubmit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandleSubmit
        // TODO add your handling code here:
        
        Campaigns camp = new Campaigns();
        camp.setCampaignName(campaignName.getText());
        camp.setAccountManagerId(Integer.parseInt(campaignManagerID.getSelectedItem().toString()));
        camp.setCampaignProduct(campaignProduct.getName());
        camp.setProductId(Integer.parseInt(campaignProductID.getSelectedItem().toString()));
        camp.setCampaignManager(campaignManager.getName());
        camp.setCampaignType(campaignType.getName());
        camp.setCampaignSalesValueTarget(Integer.parseInt(salesValue.getText()));
        camp.setCampaignSalesVolumeTarget(Integer.parseInt(salesVolume.getText()));
        
        DateCleanser cleanser = new DateCleanser(campaignStart.getText());
        camp.setCampaignStart(cleanser.getCleansedDate());
        
        DateCleanser cleansed = new DateCleanser(campaignEnd.getText());
        camp.setCampaignEnd(cleansed.getCleansedDate());
        
        
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("CRMApplicationDesktopPU");
        EntityManager em = emf.createEntityManager();
        
        em.getTransaction().begin();
        em.persist(camp);
        em.getTransaction().commit();
        em.close();
        emf.close();
        
    }//GEN-LAST:event_HandleSubmit

    private void HandleResetform(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandleResetform
        campaignName.setText("");
        campaignManagerID.setSelectedItem("Please select"); campaignProduct.setSelectedItem("Please select"); 
        campaignProduct.setSelectedItem("Please select");
        campaignProductID.setSelectedItem("Please select");
        campaignManager.setSelectedItem(("Please select"));
        campaignType.setSelectedItem(("Please select"));
        salesValue.setText("");
        salesVolume.setText("");
        campaignStart.setText(""); 
        campaignEnd.setText("");
    }//GEN-LAST:event_HandleResetform

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCampaign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCampaign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCampaign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCampaign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCampaign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campManagerLabel;
    private javax.swing.JTextField campaignEnd;
    private javax.swing.JLabel campaignEndLabel;
    private javax.swing.JComboBox<String> campaignManager;
    private javax.swing.JComboBox<String> campaignManagerID;
    private javax.swing.JLabel campaignManagerIDLabel;
    private javax.swing.JTextField campaignName;
    private javax.swing.JLabel campaignNameLabel;
    private javax.swing.JComboBox<String> campaignProduct;
    private javax.swing.JComboBox<String> campaignProductID;
    private javax.swing.JLabel campaignProductIDLabel;
    private javax.swing.JLabel campaignProductLabel;
    private javax.swing.JTextField campaignStart;
    private javax.swing.JLabel campaignStartLabel;
    private javax.swing.JComboBox<String> campaignType;
    private javax.swing.JLabel campaignTypeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField salesValue;
    private javax.swing.JLabel salesValueLabel;
    private javax.swing.JTextField salesVolume;
    private javax.swing.JLabel salesVolumeLabel;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
