package crmapplicationdesktop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import crmapplicationdesktop.entity.*;
import javax.persistence.*;
import java.util.*;
/**
 *
 * @author user
 */
public class CampaignEnrollment extends javax.swing.JFrame {

    /**
     * Creates new form CampaignEnrollment
     */
    public CampaignEnrollment() {
        initComponents();
        getProducts();
        getCustomers();
        getCampaigns();
        populateManagers();
    }

    //Let's share from the products, campaigns, managers, and customers entities - with which data shall be mapped upon the combo box elements
    //If this becomes repetetive across new components - then we should follow the rule of three to modularize these utilities
     EntityManagerFactory emf = Persistence.createEntityManagerFactory("CRMApplicationDesktopPU");
        EntityManager em = emf.createEntityManager();
        
          //create a query to retrieve all account managers
        TypedQuery<Accountmanagers> query = em.createQuery("SELECT c FROM Accountmanagers c", Accountmanagers.class);
        List<Accountmanagers> MANAGERS = query.getResultList();
        
        //create query to retrieve product information
        TypedQuery<Products> productQuery = em.createQuery("SELECT p FROM Products p", Products.class);
        List<Products> PRODUCTS = productQuery.getResultList();
        
        //create query to retreive customer information
        TypedQuery<Customers> customer = em.createQuery("SELECT cus FROM Customers cus", Customers.class);
        List<Customers> CUSTOMERLIST = customer.getResultList();
        
        //create query to retreive ccampaign information
        TypedQuery<Campaigns> campaign = em.createQuery("SELECT camp FROM Campaigns camp", Campaigns.class);
        List<Campaigns> CAMPAIGNLIST = campaign.getResultList();
        
        
//Use these methods to map data unto the combo box elements - so that they are called when this window is activated
        private void getCampaigns(){
            for(Campaigns camp: CAMPAIGNLIST){
                campaignID.addItem(camp.getCampaignId().toString());
                campaignName.addItem(camp.getCampaignName());
            }
        }
        
        private void populateManagers(){
         for(Accountmanagers person: MANAGERS){
             accountManagerID.addItem(person.getAccountManagerId().toString());
             String fullname = person.getFirstName() + " " + person.getLastName();
             accountManagerName.addItem(fullname);
         }
     }
        
        private void getCustomers(){
            for(Customers cust: CUSTOMERLIST){
            customerID.addItem(cust.getCustomerId().toString());
        }
        }
        
        private void getProducts(){
            for(Products product: PRODUCTS){
                campaignProduct1.addItem(product.getProductId().toString());
            }
        }
        
        
        
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        JHeader = new javax.swing.JLabel();
        campaignNameLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        campaignIDLabel = new javax.swing.JLabel();
        acctMgrNameLabel = new javax.swing.JLabel();
        respondedLabel = new javax.swing.JLabel();
        acctMgrLabel = new javax.swing.JLabel();
        campaignContentLabel = new javax.swing.JLabel();
        respondedYes = new javax.swing.JCheckBox();
        respondedNo = new javax.swing.JCheckBox();
        customerIDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        submitBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        campaignProductLabel = new javax.swing.JLabel();
        campaignID = new javax.swing.JComboBox<>();
        accountManagerID = new javax.swing.JComboBox<>();
        campaignName = new javax.swing.JComboBox<>();
        accountManagerName = new javax.swing.JComboBox<>();
        customerID = new javax.swing.JComboBox<>();
        campaignProduct1 = new javax.swing.JComboBox<>();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JHeader.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        JHeader.setText("Campaign Enrollment");

        campaignNameLabel.setText("Campaign Name");

        jTextField1.setText("jTextField1");

        campaignIDLabel.setText("Campaign ID");

        acctMgrNameLabel.setText("Account Manager Name");

        respondedLabel.setText("Has Responded?");

        acctMgrLabel.setText("Account Manager ID");

        campaignContentLabel.setText("Campaign Content");

        respondedYes.setText("Yes");
        respondedYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respondedYesActionPerformed(evt);
            }
        });

        respondedNo.setText("No");
        respondedNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respondedNoActionPerformed(evt);
            }
        });

        customerIDLabel.setText("Customer ID");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HandleSubmit(evt);
            }
        });

        resetBtn.setText("Reset");

        campaignProductLabel.setText("Campaign Product");

        campaignID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        accountManagerID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        campaignName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));
        campaignName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campaignNameActionPerformed(evt);
            }
        });

        accountManagerName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        customerID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        campaignProduct1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitBtn)
                                .addGap(12, 12, 12)
                                .addComponent(resetBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(respondedYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(respondedNo))
                            .addComponent(campaignProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                            .addComponent(campaignIDLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campaignNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctMgrLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctMgrNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respondedLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campaignContentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIDLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campaignID, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campaignName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountManagerID, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountManagerName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campaignProduct1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerID, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(698, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(621, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(622, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campaignIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(campaignID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campaignNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(campaignName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(acctMgrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(accountManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(acctMgrNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campaignProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(campaignProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(respondedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respondedYes)
                    .addComponent(respondedNo))
                .addGap(18, 18, 18)
                .addComponent(campaignContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(resetBtn))
                .addGap(79, 79, 79))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(491, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(467, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void respondedYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respondedYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respondedYesActionPerformed

    private void respondedNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respondedNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respondedNoActionPerformed

    
    //This Handles the submission of the Campaign Enrollment form
    private void HandleSubmit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandleSubmit
        
        Campaignenrollments enr = new Campaignenrollments();
        
        enr.setCampaignId(Integer.parseInt(campaignID.getName()));
        enr.setCampaignName(campaignName.getName());
        enr.setAccountManagerId(Integer.parseInt(accountManagerID.getName()));
        enr.setCampaignManager(accountManagerName.getName());
        enr.setCustomerId(Integer.parseInt(customerID.getName()));
        enr.setCampaignContent(jTextArea1.getText());
        enr.setProductId(Integer.parseInt(campaignProduct1.getName()));
        
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("CRMApplicationDesktopPU");
        EntityManager em = emf.createEntityManager();
        
        em.getTransaction().begin();
        em.persist(enr);
        em.getTransaction().commit();
        em.close();
        emf.close();
        
    }//GEN-LAST:event_HandleSubmit

    private void campaignNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campaignNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campaignNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampaignEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampaignEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampaignEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampaignEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampaignEnrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JHeader;
    private javax.swing.JComboBox<String> accountManagerID;
    private javax.swing.JComboBox<String> accountManagerName;
    private javax.swing.JLabel acctMgrLabel;
    private javax.swing.JLabel acctMgrNameLabel;
    private javax.swing.JLabel campaignContentLabel;
    private javax.swing.JComboBox<String> campaignID;
    private javax.swing.JLabel campaignIDLabel;
    private javax.swing.JComboBox<String> campaignName;
    private javax.swing.JLabel campaignNameLabel;
    private javax.swing.JComboBox<String> campaignProduct1;
    private javax.swing.JLabel campaignProductLabel;
    private javax.swing.JComboBox<String> customerID;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel respondedLabel;
    private javax.swing.JCheckBox respondedNo;
    private javax.swing.JCheckBox respondedYes;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
