/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crmapplicationdesktop;

/**
 *
 * @author user
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopBody = new javax.swing.JPanel();
        infoMGTPane1 = new javax.swing.JPanel();
        HomepagePanel = new javax.swing.JPanel();
        homepageLabel = new javax.swing.JLabel();
        accountManagerPane = new javax.swing.JPanel();
        acctmgrLabel = new javax.swing.JLabel();
        customersPane = new javax.swing.JPanel();
        customersPanelLabel = new javax.swing.JLabel();
        productPane = new javax.swing.JPanel();
        productPanelLabel = new javax.swing.JLabel();
        campaignsPane = new javax.swing.JPanel();
        campaignsPanelLabel = new javax.swing.JLabel();
        enrollmentPane = new javax.swing.JPanel();
        enrollmentPanelLabel = new javax.swing.JLabel();
        infoMGTPane = new javax.swing.JPanel();
        marketingfunnelLabel = new javax.swing.JLabel();
        marketingFunnelPane = new javax.swing.JPanel();
        infoMGTPanelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));

        desktopBody.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout infoMGTPane1Layout = new javax.swing.GroupLayout(infoMGTPane1);
        infoMGTPane1.setLayout(infoMGTPane1Layout);
        infoMGTPane1Layout.setHorizontalGroup(
            infoMGTPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1345, Short.MAX_VALUE)
        );
        infoMGTPane1Layout.setVerticalGroup(
            infoMGTPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        desktopBody.add(infoMGTPane1, java.awt.BorderLayout.PAGE_START);

        HomepagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowHomepage(evt);
            }
        });

        homepageLabel.setText("Home Page");

        javax.swing.GroupLayout HomepagePanelLayout = new javax.swing.GroupLayout(HomepagePanel);
        HomepagePanel.setLayout(HomepagePanelLayout);
        HomepagePanelLayout.setHorizontalGroup(
            HomepagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomepagePanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(homepageLabel)
                .addGap(21, 21, 21))
        );
        HomepagePanelLayout.setVerticalGroup(
            HomepagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomepagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homepageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accountManagerPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowAccountManager(evt);
            }
        });

        acctmgrLabel.setText("Account Manager");

        javax.swing.GroupLayout accountManagerPaneLayout = new javax.swing.GroupLayout(accountManagerPane);
        accountManagerPane.setLayout(accountManagerPaneLayout);
        accountManagerPaneLayout.setHorizontalGroup(
            accountManagerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountManagerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acctmgrLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        accountManagerPaneLayout.setVerticalGroup(
            accountManagerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountManagerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acctmgrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customersPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowCustomers(evt);
            }
        });

        customersPanelLabel.setText("Customers");

        javax.swing.GroupLayout customersPaneLayout = new javax.swing.GroupLayout(customersPane);
        customersPane.setLayout(customersPaneLayout);
        customersPaneLayout.setHorizontalGroup(
            customersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customersPanelLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        customersPaneLayout.setVerticalGroup(
            customersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customersPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowProducts(evt);
            }
        });

        productPanelLabel.setText("Products");

        javax.swing.GroupLayout productPaneLayout = new javax.swing.GroupLayout(productPane);
        productPane.setLayout(productPaneLayout);
        productPaneLayout.setHorizontalGroup(
            productPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(productPanelLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        productPaneLayout.setVerticalGroup(
            productPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        campaignsPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowCampaigns(evt);
            }
        });

        campaignsPanelLabel.setText("Campaigns");

        javax.swing.GroupLayout campaignsPaneLayout = new javax.swing.GroupLayout(campaignsPane);
        campaignsPane.setLayout(campaignsPaneLayout);
        campaignsPaneLayout.setHorizontalGroup(
            campaignsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campaignsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campaignsPanelLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        campaignsPaneLayout.setVerticalGroup(
            campaignsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campaignsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campaignsPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enrollmentPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowEnrollment(evt);
            }
        });

        enrollmentPanelLabel.setText("Campaign Enrollment");

        javax.swing.GroupLayout enrollmentPaneLayout = new javax.swing.GroupLayout(enrollmentPane);
        enrollmentPane.setLayout(enrollmentPaneLayout);
        enrollmentPaneLayout.setHorizontalGroup(
            enrollmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrollmentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enrollmentPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        enrollmentPaneLayout.setVerticalGroup(
            enrollmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrollmentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enrollmentPanelLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        marketingfunnelLabel.setText("Marketing Funnel");
        marketingfunnelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowFunnel(evt);
            }
        });

        javax.swing.GroupLayout infoMGTPaneLayout = new javax.swing.GroupLayout(infoMGTPane);
        infoMGTPane.setLayout(infoMGTPaneLayout);
        infoMGTPaneLayout.setHorizontalGroup(
            infoMGTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoMGTPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(marketingfunnelLabel)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        infoMGTPaneLayout.setVerticalGroup(
            infoMGTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoMGTPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marketingfunnelLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout marketingFunnelPaneLayout = new javax.swing.GroupLayout(marketingFunnelPane);
        marketingFunnelPane.setLayout(marketingFunnelPaneLayout);
        marketingFunnelPaneLayout.setHorizontalGroup(
            marketingFunnelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        marketingFunnelPaneLayout.setVerticalGroup(
            marketingFunnelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        infoMGTPanelLabel.setText("Information Management");
        infoMGTPanelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowInfoMgt(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomepagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountManagerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customersPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campaignsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enrollmentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoMGTPanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoMGTPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marketingFunnelPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(enrollmentPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campaignsPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customersPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accountManagerPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomepagePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoMGTPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(marketingFunnelPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(infoMGTPanelLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopBody, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Event handlers that display certain tabbed pages
    private void HandleShowHomepage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowHomepage
        Homepage page = new Homepage();
        page.show();
    }//GEN-LAST:event_HandleShowHomepage

    private void HandleShowAccountManager(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowAccountManager
        AddAccountManager  acct = new AddAccountManager();
        acct.show();
    }//GEN-LAST:event_HandleShowAccountManager

    private void HandleShowCustomers(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowCustomers
        
        AddCustomer cust = new AddCustomer();
        cust.show();
    }//GEN-LAST:event_HandleShowCustomers

    private void HandleShowProducts(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowProducts
       AddProduct prod = new AddProduct();
       prod.show();
    }//GEN-LAST:event_HandleShowProducts

    private void HandleShowCampaigns(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowCampaigns
        AddCampaign camp = new AddCampaign();
        camp.show();
    }//GEN-LAST:event_HandleShowCampaigns

    private void HandleShowEnrollment(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowEnrollment
        
        CampaignEnrollment enroll = new CampaignEnrollment();
        enroll.show();
    }//GEN-LAST:event_HandleShowEnrollment

    private void HandleShowFunnel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowFunnel
      MarketingFunnel funnel = new MarketingFunnel();
      funnel.show();
    }//GEN-LAST:event_HandleShowFunnel

    private void HandleShowInfoMgt(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowInfoMgt
        InformationManagement mgt = new InformationManagement();
        mgt.show();
    }//GEN-LAST:event_HandleShowInfoMgt

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomepagePanel;
    private javax.swing.JPanel accountManagerPane;
    private javax.swing.JLabel acctmgrLabel;
    private javax.swing.JPanel campaignsPane;
    private javax.swing.JLabel campaignsPanelLabel;
    private javax.swing.JPanel customersPane;
    private javax.swing.JLabel customersPanelLabel;
    private javax.swing.JPanel desktopBody;
    private javax.swing.JPanel enrollmentPane;
    private javax.swing.JLabel enrollmentPanelLabel;
    private javax.swing.JLabel homepageLabel;
    private javax.swing.JPanel infoMGTPane;
    private javax.swing.JPanel infoMGTPane1;
    private javax.swing.JLabel infoMGTPanelLabel;
    private javax.swing.JPanel marketingFunnelPane;
    private javax.swing.JLabel marketingfunnelLabel;
    private javax.swing.JPanel productPane;
    private javax.swing.JLabel productPanelLabel;
    // End of variables declaration//GEN-END:variables
}
