/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crmapplicationdesktop;

/**
 *
 * @author user
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopBody = new javax.swing.JPanel();
        infoMGTPane1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        acctManagerMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stockQuotePanel = new javax.swing.JPanel();
        stockQoutePanelLabel = new javax.swing.JLabel();
        HomepagePanel = new javax.swing.JPanel();
        homepageLabel = new javax.swing.JLabel();
        accountManagerPane = new javax.swing.JPanel();
        acctmgrLabel = new javax.swing.JLabel();
        customersPane = new javax.swing.JPanel();
        customersPanelLabel = new javax.swing.JLabel();
        productPane = new javax.swing.JPanel();
        productPanelLabel = new javax.swing.JLabel();
        campaignsPane = new javax.swing.JPanel();
        campaignsPanelLabel = new javax.swing.JLabel();
        enrollmentPane = new javax.swing.JPanel();
        enrollmentPanelLabel = new javax.swing.JLabel();
        infoMGTPane = new javax.swing.JPanel();
        marketingfunnelLabel = new javax.swing.JLabel();
        infoMGTPanelLabel = new javax.swing.JLabel();
        stockQuoteMenu = new javax.swing.JPanel();
        stockQuoteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));

        desktopBody.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout infoMGTPane1Layout = new javax.swing.GroupLayout(infoMGTPane1);
        infoMGTPane1.setLayout(infoMGTPane1Layout);
        infoMGTPane1Layout.setHorizontalGroup(
            infoMGTPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1345, Short.MAX_VALUE)
        );
        infoMGTPane1Layout.setVerticalGroup(
            infoMGTPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        acctManagerMenu.setBackground(new java.awt.Color(250, 250, 250));
        acctManagerMenu.setForeground(new java.awt.Color(255, 255, 255));
        acctManagerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoManagers(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Add Account Managers");

        javax.swing.GroupLayout acctManagerMenuLayout = new javax.swing.GroupLayout(acctManagerMenu);
        acctManagerMenu.setLayout(acctManagerMenuLayout);
        acctManagerMenuLayout.setHorizontalGroup(
            acctManagerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(acctManagerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(acctManagerMenuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        acctManagerMenuLayout.setVerticalGroup(
            acctManagerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(acctManagerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(acctManagerMenuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(acctManagerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(acctManagerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoCustomer(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Add Customers");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoProducts(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Add Products");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel3)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoCampaign(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Add Campaigns");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel4)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoEnrollments(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Campaign Enrollment");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoInfoMgt(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Information Management");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoFunnel(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("Marketing Funnel");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setText("Good Day, Admin");

        stockQuotePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoStockQuotes(evt);
            }
        });

        stockQoutePanelLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        stockQoutePanelLabel.setText("Stock Quotes");

        javax.swing.GroupLayout stockQuotePanelLayout = new javax.swing.GroupLayout(stockQuotePanel);
        stockQuotePanel.setLayout(stockQuotePanelLayout);
        stockQuotePanelLayout.setHorizontalGroup(
            stockQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stockQuotePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stockQoutePanelLabel)
                .addGap(89, 89, 89))
        );
        stockQuotePanelLayout.setVerticalGroup(
            stockQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockQuotePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(stockQoutePanelLabel)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout desktopBodyLayout = new javax.swing.GroupLayout(desktopBody);
        desktopBody.setLayout(desktopBodyLayout);
        desktopBodyLayout.setHorizontalGroup(
            desktopBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoMGTPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(desktopBodyLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(desktopBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(desktopBodyLayout.createSequentialGroup()
                        .addGroup(desktopBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopBodyLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopBodyLayout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(desktopBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stockQuotePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        desktopBodyLayout.setVerticalGroup(
            desktopBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopBodyLayout.createSequentialGroup()
                .addComponent(infoMGTPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addGap(48, 48, 48)
                .addGroup(desktopBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(desktopBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockQuotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        HomepagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowHomepage(evt);
            }
        });

        homepageLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        homepageLabel.setText("Funnel");

        javax.swing.GroupLayout HomepagePanelLayout = new javax.swing.GroupLayout(HomepagePanel);
        HomepagePanel.setLayout(HomepagePanelLayout);
        HomepagePanelLayout.setHorizontalGroup(
            HomepagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomepagePanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(homepageLabel)
                .addGap(21, 21, 21))
        );
        HomepagePanelLayout.setVerticalGroup(
            HomepagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomepagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homepageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accountManagerPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowAccountManager(evt);
            }
        });

        acctmgrLabel.setText("Account Manager");

        javax.swing.GroupLayout accountManagerPaneLayout = new javax.swing.GroupLayout(accountManagerPane);
        accountManagerPane.setLayout(accountManagerPaneLayout);
        accountManagerPaneLayout.setHorizontalGroup(
            accountManagerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountManagerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acctmgrLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        accountManagerPaneLayout.setVerticalGroup(
            accountManagerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountManagerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acctmgrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customersPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowCustomers(evt);
            }
        });

        customersPanelLabel.setText("Customers");

        javax.swing.GroupLayout customersPaneLayout = new javax.swing.GroupLayout(customersPane);
        customersPane.setLayout(customersPaneLayout);
        customersPaneLayout.setHorizontalGroup(
            customersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customersPanelLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        customersPaneLayout.setVerticalGroup(
            customersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customersPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowProducts(evt);
            }
        });

        productPanelLabel.setText("Products");

        javax.swing.GroupLayout productPaneLayout = new javax.swing.GroupLayout(productPane);
        productPane.setLayout(productPaneLayout);
        productPaneLayout.setHorizontalGroup(
            productPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(productPanelLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        productPaneLayout.setVerticalGroup(
            productPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        campaignsPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowCampaigns(evt);
            }
        });

        campaignsPanelLabel.setText("Campaigns");

        javax.swing.GroupLayout campaignsPaneLayout = new javax.swing.GroupLayout(campaignsPane);
        campaignsPane.setLayout(campaignsPaneLayout);
        campaignsPaneLayout.setHorizontalGroup(
            campaignsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campaignsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campaignsPanelLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        campaignsPaneLayout.setVerticalGroup(
            campaignsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campaignsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campaignsPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enrollmentPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowEnrollment(evt);
            }
        });

        enrollmentPanelLabel.setText("Campaign Enrollment");

        javax.swing.GroupLayout enrollmentPaneLayout = new javax.swing.GroupLayout(enrollmentPane);
        enrollmentPane.setLayout(enrollmentPaneLayout);
        enrollmentPaneLayout.setHorizontalGroup(
            enrollmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrollmentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enrollmentPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        enrollmentPaneLayout.setVerticalGroup(
            enrollmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrollmentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enrollmentPanelLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        marketingfunnelLabel.setText("Marketing Funnel");
        marketingfunnelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowFunnel(evt);
            }
        });

        javax.swing.GroupLayout infoMGTPaneLayout = new javax.swing.GroupLayout(infoMGTPane);
        infoMGTPane.setLayout(infoMGTPaneLayout);
        infoMGTPaneLayout.setHorizontalGroup(
            infoMGTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoMGTPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(marketingfunnelLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        infoMGTPaneLayout.setVerticalGroup(
            infoMGTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoMGTPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marketingfunnelLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        infoMGTPanelLabel.setText("Information Management");
        infoMGTPanelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleShowInfoMgt(evt);
            }
        });

        stockQuoteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HandleStockQuote(evt);
            }
        });

        stockQuoteLabel.setText("Stock Qoutes");

        javax.swing.GroupLayout stockQuoteMenuLayout = new javax.swing.GroupLayout(stockQuoteMenu);
        stockQuoteMenu.setLayout(stockQuoteMenuLayout);
        stockQuoteMenuLayout.setHorizontalGroup(
            stockQuoteMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockQuoteMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(stockQuoteLabel)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        stockQuoteMenuLayout.setVerticalGroup(
            stockQuoteMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockQuoteMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stockQuoteLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomepagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountManagerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customersPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campaignsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enrollmentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoMGTPanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoMGTPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockQuoteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enrollmentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campaignsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customersPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountManagerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HomepagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoMGTPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(infoMGTPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stockQuoteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Event handlers that display certain tabbed pages
    private void HandleShowHomepage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowHomepage
        Homepage page = new Homepage();
        page.show();
    }//GEN-LAST:event_HandleShowHomepage

    private void HandleShowAccountManager(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowAccountManager
        AddAccountManager  acct = new AddAccountManager();
        acct.show();
    }//GEN-LAST:event_HandleShowAccountManager

    private void HandleShowCustomers(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowCustomers
        
        AddCustomer cust = new AddCustomer();
        cust.show();
    }//GEN-LAST:event_HandleShowCustomers

    private void HandleShowProducts(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowProducts
       AddProduct prod = new AddProduct();
       prod.show();
    }//GEN-LAST:event_HandleShowProducts

    private void HandleShowCampaigns(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowCampaigns
        AddCampaign camp = new AddCampaign();
        camp.show();
    }//GEN-LAST:event_HandleShowCampaigns

    private void HandleShowEnrollment(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowEnrollment
        
        CampaignEnrollment enroll = new CampaignEnrollment();
        enroll.show();
    }//GEN-LAST:event_HandleShowEnrollment

    private void HandleShowFunnel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowFunnel
      MarketingFunnel funnel = new MarketingFunnel();
      funnel.show();
    }//GEN-LAST:event_HandleShowFunnel

    private void HandleShowInfoMgt(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleShowInfoMgt
        InformationManagement mgt = new InformationManagement();
        mgt.show();
    }//GEN-LAST:event_HandleShowInfoMgt

    private void gotoManagers(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoManagers
        AddAccountManager  acct = new AddAccountManager();
        acct.show();
    }//GEN-LAST:event_gotoManagers

    private void gotoCustomer(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoCustomer
        // TODO add your handling code here:
        AddCustomer cust = new AddCustomer();
        cust.show();
    }//GEN-LAST:event_gotoCustomer

    private void gotoProducts(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoProducts
        // TODO add your handling code here:
         AddProduct prod = new AddProduct();
       prod.show();
    }//GEN-LAST:event_gotoProducts

    private void gotoCampaign(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoCampaign
        // TODO add your handling code here:
        AddCampaign camp = new AddCampaign();
        camp.show();
    }//GEN-LAST:event_gotoCampaign

    private void gotoEnrollments(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoEnrollments
        // TODO add your handling code here:
          
        CampaignEnrollment enroll = new CampaignEnrollment();
        enroll.show();
    }//GEN-LAST:event_gotoEnrollments

    private void gotoInfoMgt(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoInfoMgt
        // TODO add your handling code here:
        InformationManagement mgt = new InformationManagement();
        mgt.show();
    }//GEN-LAST:event_gotoInfoMgt

    private void gotoFunnel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoFunnel
        // TODO add your handling code here:
         MarketingFunnel funnel = new MarketingFunnel();
      funnel.show();
    }//GEN-LAST:event_gotoFunnel

    private void HandleStockQuote(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HandleStockQuote
        // TODO add your handling code here:
        StockQuotes finances = new StockQuotes();
        finances.show();
    }//GEN-LAST:event_HandleStockQuote

    private void gotoStockQuotes(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoStockQuotes
        // TODO add your handling code here:
        StockQuotes fin = new StockQuotes();
        fin.setVisible(true);
    }//GEN-LAST:event_gotoStockQuotes

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomepagePanel;
    private javax.swing.JPanel accountManagerPane;
    private javax.swing.JPanel acctManagerMenu;
    private javax.swing.JLabel acctmgrLabel;
    private javax.swing.JPanel campaignsPane;
    private javax.swing.JLabel campaignsPanelLabel;
    private javax.swing.JPanel customersPane;
    private javax.swing.JLabel customersPanelLabel;
    private javax.swing.JPanel desktopBody;
    private javax.swing.JPanel enrollmentPane;
    private javax.swing.JLabel enrollmentPanelLabel;
    private javax.swing.JLabel homepageLabel;
    private javax.swing.JPanel infoMGTPane;
    private javax.swing.JPanel infoMGTPane1;
    private javax.swing.JLabel infoMGTPanelLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel marketingfunnelLabel;
    private javax.swing.JPanel productPane;
    private javax.swing.JLabel productPanelLabel;
    private javax.swing.JLabel stockQoutePanelLabel;
    private javax.swing.JLabel stockQuoteLabel;
    private javax.swing.JPanel stockQuoteMenu;
    private javax.swing.JPanel stockQuotePanel;
    // End of variables declaration//GEN-END:variables
}
