/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crmapplicationdesktop;

import crmapplicationdesktop.entity.*;
import java.util.*;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;


/**
 *
 * @author user
 */
public class MarketingFunnel extends javax.swing.JFrame {

    /**
     * Creates new form MarketingFunnel
     */
    public MarketingFunnel() {
        initComponents();
        populateCampaigns();
        mapValuesOnFunnel();
    }
    
    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("CRMApplicationDesktopPU");
        EntityManager em = emf.createEntityManager();
        
    //create a query to retrieve all account managers
        TypedQuery<Campaignenrollments> query = em.createQuery("SELECT c FROM Campaignenrollments c", Campaignenrollments.class);
        List<Campaignenrollments> CAMPAIGNENROLLMENTS = query.getResultList();
        
        
        //Feed UI with data from campaigns - so that in future, we can dynamically show makreting funnel for each campaign
        private void populateCampaigns(){
            for(Campaignenrollments cam: CAMPAIGNENROLLMENTS){
                chooseCampaign.addItem(cam.getCampaignName());
            }
            chooseCampaign.setEditable(false);
        }
        
        
        //Set Values to funnel visualization to show percentages for prospects & leads - We could use this as a global functionality as the app expands
private void mapValuesOnFunnel() {
    if (CAMPAIGNENROLLMENTS == null) {
        System.err.println("CAMPAIGNENROLLMENTS is null");
        updateUIWithDefaultValues();
        return;
    }

    if (CAMPAIGNENROLLMENTS.isEmpty()) {
        System.err.println("CAMPAIGNENROLLMENTS is empty");
        updateUIWithDefaultValues();
        return;
    }

    long falseCount = CAMPAIGNENROLLMENTS.stream()
            .filter(Objects::nonNull)
            .map(cam -> {
                try {
                    return cam.getHasResponded();
                } catch (NullPointerException e) {
                    System.err.println("NullPointerException in getHasResponded for campaign: " + cam);
                    return null;
                }
            })
            .filter(Objects::nonNull)
            .filter(hasResponded -> !hasResponded)
            .count();
    
    int totalResponses = CAMPAIGNENROLLMENTS.size();
    long trueCount = totalResponses - falseCount;
    
    int percentageProspects = totalResponses > 0 ? (int) ((falseCount * 100.0) / totalResponses) : 0;
    int percentageLeads = totalResponses > 0 ? (int) ((trueCount * 100.0) / totalResponses) : 0;
    
    updateUIWithValues(percentageProspects, percentageLeads);
}

private void updateUIWithDefaultValues() {
    updateUIWithValues(0, 0);
}

private void updateUIWithValues(int percentageProspects, int percentageLeads) {
    if (prospectValue != null) {
        prospectValue.setText(percentageProspects + "%");
    } else {
        System.err.println("prospectValue is null");
    }
    
    if (leadsValue != null) {
        leadsValue.setText(percentageLeads + "%");
    } else {
        System.err.println("leadsValue is null");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prospects = new javax.swing.JTextField();
        leads = new javax.swing.JTextField();
        conversions = new javax.swing.JTextField();
        prospectValue = new javax.swing.JTextField();
        leadsValue = new javax.swing.JTextField();
        conversionsValue = new javax.swing.JTextField();
        chooseCampaign = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Marketing Funnel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 243, 30));

        prospects.setEditable(false);
        prospects.setBackground(new java.awt.Color(0, 102, 153));
        prospects.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        prospects.setForeground(new java.awt.Color(255, 255, 255));
        prospects.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prospects.setText("Prospects");
        prospects.setToolTipText("All Propspects enrolled in campaigns");
        getContentPane().add(prospects, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 185, 634, 77));

        leads.setEditable(false);
        leads.setBackground(new java.awt.Color(0, 153, 153));
        leads.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        leads.setForeground(new java.awt.Color(255, 255, 255));
        leads.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        leads.setText("Leads");
        leads.setToolTipText("All leads signed up to campaigns");
        getContentPane().add(leads, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 274, 434, 77));

        conversions.setEditable(false);
        conversions.setBackground(new java.awt.Color(51, 255, 204));
        conversions.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        conversions.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        conversions.setText("Conversions");
        conversions.setToolTipText("All conversions acheived from campaigns");
        getContentPane().add(conversions, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 357, 282, 77));

        prospectValue.setEditable(false);
        prospectValue.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        prospectValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(prospectValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 189, 95, 34));

        leadsValue.setEditable(false);
        leadsValue.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        leadsValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        leadsValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadsValueActionPerformed(evt);
            }
        });
        getContentPane().add(leadsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 274, 95, 34));

        conversionsValue.setEditable(false);
        conversionsValue.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        conversionsValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(conversionsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 355, 95, 34));

        chooseCampaign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Viewing Overall" }));
        getContentPane().add(chooseCampaign, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 135, 195, -1));

        jLabel2.setText("Select Campaign");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 112, 148, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leadsValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leadsValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leadsValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketingFunnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketingFunnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketingFunnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketingFunnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketingFunnel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseCampaign;
    private javax.swing.JTextField conversions;
    private javax.swing.JTextField conversionsValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField leads;
    private javax.swing.JTextField leadsValue;
    private javax.swing.JTextField prospectValue;
    private javax.swing.JTextField prospects;
    // End of variables declaration//GEN-END:variables
}
