/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crmapplicationdesktop;

import YahooFinance.GetStocks;
import java.awt.Color;
import javax.swing.*;
import org.json.*;





/**
 *
 * @author user
 */
public class StockQuotes extends javax.swing.JFrame {
    String symbol;
    String region;
    String language;

    /**
     * Creates new form Yahoo_Finance
     */
    
    public StockQuotes() {
        initComponents();
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterStock = new javax.swing.JTextField();
        stockLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockResults = new javax.swing.JTextArea();
        searchStockBtn = new javax.swing.JButton();
        regionText = new javax.swing.JTextField();
        regionLabel = new javax.swing.JLabel();
        languageLabel = new javax.swing.JLabel();
        languageText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        symbolResultLabel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        performanceLabel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        performanceText = new javax.swing.JPanel();
        sectorAvgLabel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        sectorAvgText = new javax.swing.JPanel();
        stockSymbolText = new javax.swing.JTextField();
        scoreText = new javax.swing.JTextField();
        performanceResult = new javax.swing.JTextField();
        sectorAverage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        developmentResults = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Funnel Stock Quotes (Powered by Yahoo Finance)");

        stockLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        stockLabel.setText("Stock Symbol (eg MSFT, AAPL)");

        stockResults.setEditable(false);
        stockResults.setBackground(new java.awt.Color(255, 255, 255));
        stockResults.setColumns(20);
        stockResults.setRows(5);
        jScrollPane1.setViewportView(stockResults);

        searchStockBtn.setBackground(new java.awt.Color(0, 153, 204));
        searchStockBtn.setText("Search Stock");
        searchStockBtn.setToolTipText("Search");
        searchStockBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HandleGetQoutes(evt);
            }
        });

        regionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        regionLabel.setText("Region");

        languageLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        languageLabel.setText("Language");

        languageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageTextActionPerformed(evt);
            }
        });

        symbolResultLabel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Stock Symbol");

        javax.swing.GroupLayout symbolResultLabelLayout = new javax.swing.GroupLayout(symbolResultLabel);
        symbolResultLabel.setLayout(symbolResultLabelLayout);
        symbolResultLabelLayout.setHorizontalGroup(
            symbolResultLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(symbolResultLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(symbolResultLabelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        symbolResultLabelLayout.setVerticalGroup(
            symbolResultLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(symbolResultLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, symbolResultLabelLayout.createSequentialGroup()
                    .addContainerGap(9, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        scoreLabel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("Score");

        javax.swing.GroupLayout scoreLabelLayout = new javax.swing.GroupLayout(scoreLabel);
        scoreLabel.setLayout(scoreLabelLayout);
        scoreLabelLayout.setHorizontalGroup(
            scoreLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(scoreLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(scoreLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        scoreLabelLayout.setVerticalGroup(
            scoreLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(scoreLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(scoreLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        performanceLabel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Performance");

        javax.swing.GroupLayout performanceLabelLayout = new javax.swing.GroupLayout(performanceLabel);
        performanceLabel.setLayout(performanceLabelLayout);
        performanceLabelLayout.setHorizontalGroup(
            performanceLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
            .addGroup(performanceLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(performanceLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        performanceLabelLayout.setVerticalGroup(
            performanceLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(performanceLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(performanceLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout performanceTextLayout = new javax.swing.GroupLayout(performanceText);
        performanceText.setLayout(performanceTextLayout);
        performanceTextLayout.setHorizontalGroup(
            performanceTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        performanceTextLayout.setVerticalGroup(
            performanceTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        sectorAvgLabel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("Sector Average");

        javax.swing.GroupLayout sectorAvgLabelLayout = new javax.swing.GroupLayout(sectorAvgLabel);
        sectorAvgLabel.setLayout(sectorAvgLabelLayout);
        sectorAvgLabelLayout.setHorizontalGroup(
            sectorAvgLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(sectorAvgLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sectorAvgLabelLayout.createSequentialGroup()
                    .addGap(0, 59, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 59, Short.MAX_VALUE)))
        );
        sectorAvgLabelLayout.setVerticalGroup(
            sectorAvgLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(sectorAvgLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sectorAvgLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout sectorAvgTextLayout = new javax.swing.GroupLayout(sectorAvgText);
        sectorAvgText.setLayout(sectorAvgTextLayout);
        sectorAvgTextLayout.setHorizontalGroup(
            sectorAvgTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        sectorAvgTextLayout.setVerticalGroup(
            sectorAvgTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        stockSymbolText.setEditable(false);

        scoreText.setEditable(false);

        performanceResult.setEditable(false);
        performanceResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceResultActionPerformed(evt);
            }
        });

        sectorAverage.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(symbolResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockSymbolText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(performanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(performanceResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sectorAverage, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(sectorAvgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(performanceText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(228, 228, 228)
                .addComponent(sectorAvgText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sectorAvgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(performanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(symbolResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(performanceText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sectorAvgText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockSymbolText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(performanceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sectorAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel2.setText("Significant Developments");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel3.setText("Raw JSON Result");

        developmentResults.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout developmentResultsLayout = new javax.swing.GroupLayout(developmentResults);
        developmentResults.setLayout(developmentResultsLayout);
        developmentResultsLayout.setHorizontalGroup(
            developmentResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        developmentResultsLayout.setVerticalGroup(
            developmentResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        resetButton.setBackground(new java.awt.Color(102, 102, 102));
        resetButton.setText("Reset");
        resetButton.setToolTipText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HandleReset(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(enterStock)
                                .addComponent(stockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(regionText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(regionLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(languageText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(languageLabel))
                            .addGap(18, 18, 18)
                            .addComponent(searchStockBtn)
                            .addGap(18, 18, 18)
                            .addComponent(resetButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(developmentResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 854, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockLabel)
                    .addComponent(regionLabel)
                    .addComponent(languageLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStockBtn)
                    .addComponent(regionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(developmentResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HandleGetQoutes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandleGetQoutes
        // TODO add your handling code here:
            
            try {

            this.symbol = enterStock.getText();
            this.region = regionText.getText();
            this.language = languageText.getText();

                GetStocks finance = new GetStocks();
                finance.getStockQuotes(symbol, region, language, new GetStocks.StockQuoteCallback() {
                    @Override
                    public void onSuccess(String dataResponse) {
                        // This method is called on the Event Dispatch Thread (EDT)
                        if (dataResponse != null) {
                            // Print data for debugging
                            System.out.println(dataResponse);

                    
                            
                            //Parse the JSON response 'stockPage'
                            JSONObject jsonObject = new JSONObject(dataResponse);
                            JSONObject finance = jsonObject.getJSONObject("finance");
                            JSONObject result = finance.getJSONObject("result");
                            JSONObject metaData = result.getJSONObject("metaData");
                            JSONObject innovations = result.getJSONObject("innovations");
                            JSONArray developments = result.getJSONArray("significantDevelopments");
                            JSONObject companyOutlook = result.getJSONObject("companyOutlookSummary");
                            
                            // Extract data
                            String symbol = metaData.getString("symbol");
                            double innovationScore = innovations.getDouble("score");
                            
                            String innovationPerformance = companyOutlook.getString("innovationPerformance");
                            
                            
                            
                            //Add text to components
                            performanceResult.setText(innovationPerformance);
                            scoreText.setText(Double.toString(innovationScore));
                            sectorAverage.setText(Double.toString(innovations.getDouble("sectorAvg")));
                            stockSymbolText.setText(symbol);
                            
                            System.out.print(developments);
                            
                            for(int i = 0; i < developments.length(); i++){
                            JSONObject innerObj = developments.getJSONObject(i);
                            
                            JLabel label = new JLabel(innerObj.getString("date"));
                            JTextArea tArea = new JTextArea(innerObj.getString("headline"));
                            
                            label.setSize(400, 100);
                            tArea.setSize(800, 300);
                            label.setBackground(Color.white);
                            tArea.setBackground(Color.white);
                            tArea.setLineWrap(true);
                            tArea.setWrapStyleWord(true);
                            tArea.setEditable(false);
                            
                           
                            developmentResults.add(label);
                            developmentResults.add(tArea);
                            
                            
                            
                        } 
                            
                            developmentResults.revalidate();
                            developmentResults.repaint();
                            

                            

                            // Update the UI component with the result
                            stockResults.setText(dataResponse);
                        } else {
                            stockResults.setText("No data received.");
                        }
                    }

                    @Override
                    public void onError(Exception e) {
                        // Handle error scenarios
                        e.printStackTrace();
                        stockResults.setText("Error: " + e.getMessage());
                    }
                });
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
    }//GEN-LAST:event_HandleGetQoutes

    private void languageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageTextActionPerformed

    private void performanceResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_performanceResultActionPerformed

    private void HandleReset(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandleReset
        enterStock.setText("");
        regionText.setText("");
        languageText.setText("");
    }//GEN-LAST:event_HandleReset

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockQuotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockQuotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockQuotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockQuotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockQuotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel developmentResults;
    private javax.swing.JTextField enterStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JTextField languageText;
    private javax.swing.JPanel performanceLabel;
    private javax.swing.JTextField performanceResult;
    private javax.swing.JPanel performanceText;
    private javax.swing.JLabel regionLabel;
    private javax.swing.JTextField regionText;
    private javax.swing.JButton resetButton;
    private javax.swing.JPanel scoreLabel;
    private javax.swing.JTextField scoreText;
    private javax.swing.JButton searchStockBtn;
    private javax.swing.JTextField sectorAverage;
    private javax.swing.JPanel sectorAvgLabel;
    private javax.swing.JPanel sectorAvgText;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JTextArea stockResults;
    private javax.swing.JTextField stockSymbolText;
    private javax.swing.JPanel symbolResultLabel;
    // End of variables declaration//GEN-END:variables
}
